'use client';
import type { LearningPath } from '@/lib/types';
import { CareerMatchScore } from './career-match-score';
import { RecommendedPath } from './recommended-path';
import { SkillGap } from './skill-gap';
import { LabourMarketSignals } from './labour-market-signals';
import { AlternativePaths } from './alternative-paths';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { motion } from 'framer-motion';
import { SkillPathMitra } from './skillpath-mitra';

interface DashboardClientProps {
  path: LearningPath;
  lang: 'en' | 'hi';
}

const content = {
    en: {
        title: "Your Personalized Learning Path",
        subtitle: "Generated by SkillPath AI to guide you towards your career goals.",
        summary_title: "AI Summary",
        export_button: "Export to PDF",
    },
    hi: {
        title: "आपकी व्यक्तिगत सीखने की राह",
        subtitle: "स्किलपाथ एआई द्वारा आपके करियर लक्ष्यों की ओर मार्गदर्शन करने के लिए तैयार किया गया है।",
        summary_title: "एआई सारांश",
        export_button: "पीडीएफ में निर्यात करें",
    }
}

export function DashboardClient({ path, lang }: DashboardClientProps) {
  const summary = lang === 'hi' ? path.summary_hi : path.summary_en;

  const handlePrint = () => {
    window.print();
  };
  
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };
  
  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        type: 'spring',
        stiffness: 100,
      },
    },
  };


  return (
    <motion.div 
      className="container mx-auto p-4 md:p-6 lg:p-8"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      <motion.div className="mb-8 grid grid-cols-1 md:grid-cols-[1fr_auto] gap-4 items-center" variants={itemVariants}>
        <div>
            <h2 className="text-3xl font-bold font-headline text-foreground">{content[lang].title}</h2>
            <p className="text-muted-foreground">{content[lang].subtitle}</p>
        </div>
        <SkillPathMitra summary={summary} lang={lang}/>
      </motion.div>

      <motion.div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 mb-6" variants={containerVariants}>
        <motion.div variants={itemVariants}>
          <CareerMatchScore score={path.career_match_score} lang={lang} />
        </motion.div>
        <motion.div variants={itemVariants}>
          <SkillGap skills={path.skill_gap} lang={lang} />
        </motion.div>
        <motion.div variants={itemVariants}>
          <LabourMarketSignals signals={path.labour_market_signals} lang={lang} />
        </motion.div>
      </motion.div>
      
      <motion.div variants={itemVariants}>
        <Card className="mb-6 glass-card">
          <CardHeader>
              <CardTitle className="font-headline text-primary">{content[lang].summary_title}</CardTitle>
          </CardHeader>
          <CardContent>
              <p className="whitespace-pre-wrap">{summary}</p>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div className="grid gap-6 lg:grid-cols-3" variants={containerVariants}>
        <motion.div className="lg:col-span-2" variants={itemVariants}>
          <RecommendedPath path={path} lang={lang} />
        </motion.div>
        <motion.div className="space-y-6" variants={itemVariants}>
          <AlternativePaths paths={path.alternative_paths} lang={lang} />
           <Card className="glass-card">
            <CardHeader>
                <CardTitle className='font-headline'>Actions</CardTitle>
            </CardHeader>
            <CardContent>
                 <Button onClick={handlePrint} className="w-full">
                    <Download className="mr-2 h-4 w-4" />
                    {content[lang].export_button}
                </Button>
            </CardContent>
           </Card>
        </motion.div>
      </motion.div>
    </motion.div>
  );
}
